# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: otp_migration.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'otp_migration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13otp_migration.proto\x12\x0bgoogle_auth\"\x92\x01\n\x10MigrationPayload\x12\x32\n\x0eotp_parameters\x18\x01 \x03(\x0b\x32\x1a.google_auth.OtpParameters\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x13\n\x0b\x62\x61tch_index\x18\x04 \x01(\x05\x12\x10\n\x08\x62\x61tch_id\x18\x05 \x01(\x05\"\xe7\x03\n\rOtpParameters\x12\x0e\n\x06secret\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06issuer\x18\x03 \x01(\t\x12\x42\n\talgorithm\x18\x04 \x01(\x0e\x32$.google_auth.OtpParameters.Algorithm:\tALGO_SHA1\x12@\n\x06\x64igits\x18\x05 \x01(\x0e\x32%.google_auth.OtpParameters.DigitCount:\tDIGIT_SIX\x12:\n\x04type\x18\x06 \x01(\x0e\x32\".google_auth.OtpParameters.OtpType:\x08OTP_TOTP\x12\x0f\n\x07\x63ounter\x18\x07 \x01(\x03\"\\\n\tAlgorithm\x12\x10\n\x0c\x41LGO_INVALID\x10\x00\x12\r\n\tALGO_SHA1\x10\x01\x12\x0f\n\x0b\x41LGO_SHA256\x10\x02\x12\x0f\n\x0b\x41LGO_SHA512\x10\x03\x12\x0c\n\x08\x41LGO_MD5\x10\x04\"?\n\nDigitCount\x12\x11\n\rDIGIT_INVALID\x10\x00\x12\r\n\tDIGIT_SIX\x10\x01\x12\x0f\n\x0b\x44IGIT_EIGHT\x10\x02\"6\n\x07OtpType\x12\x0f\n\x0bOTP_INVALID\x10\x00\x12\x0c\n\x08OTP_HOTP\x10\x01\x12\x0c\n\x08OTP_TOTP\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'otp_migration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MIGRATIONPAYLOAD']._serialized_start=37
  _globals['_MIGRATIONPAYLOAD']._serialized_end=183
  _globals['_OTPPARAMETERS']._serialized_start=186
  _globals['_OTPPARAMETERS']._serialized_end=673
  _globals['_OTPPARAMETERS_ALGORITHM']._serialized_start=460
  _globals['_OTPPARAMETERS_ALGORITHM']._serialized_end=552
  _globals['_OTPPARAMETERS_DIGITCOUNT']._serialized_start=554
  _globals['_OTPPARAMETERS_DIGITCOUNT']._serialized_end=617
  _globals['_OTPPARAMETERS_OTPTYPE']._serialized_start=619
  _globals['_OTPPARAMETERS_OTPTYPE']._serialized_end=673
# @@protoc_insertion_point(module_scope)
