"""
CPJ API - Módulo de integração com a API do CPJ Agnes
Funções reutilizáveis para autenticação, busca de dados e processamento de documentos
"""

from .api_functions import (
    api_login,
    api_logout,
    api_get,
    api_post,
    api_buscar_lancamentos,
    api_buscar_lancamentos_bmg,
    api_buscar_lancamentos_pan,
    api_buscar_lancamentos_filtro,
    sanitizar_documento,
    formatar_data_lancamento,
    api_buscar_spf,
    api_buscar_processo,
    processar_lancamentos,
    api_buscar_documentos_spf,
    api_buscar_documentos_pj,
    api_baixar_documento,
    processar_documentos_registros,
    api_buscar_processo_tarefa,
    api_buscar_processo_tarefa_por_data,
    api_buscar_processo_tarefa_filter,
    API_SESSION,
    API_TOKEN,
    get_api_session,
    get_api_token,
    set_api_credentials,
    api_atualizar_tarefa,
    api_buscar_processo_por_pj,
    api_buscar_processo_por_ficha,
    api_atualizar_processo
)

__all__ = [
    'api_login',
    'api_logout',
    'api_get',
    'api_post',
    'api_buscar_lancamentos',
    'api_buscar_lancamentos_pan',
    'api_buscar_lancamentos_filtro',
    'sanitizar_documento',
    'formatar_data_lancamento',
    'api_buscar_spf',
    'api_buscar_processo',
    'processar_lancamentos',
    'api_buscar_documentos_spf',
    'api_buscar_documentos_pj',
    'api_baixar_documento',
    'processar_documentos_registros',
    'api_buscar_processo_tarefa',
    'api_buscar_processo_tarefa_por_data',
    'api_buscar_processo_tarefa_filter',
    'API_SESSION',
    'API_TOKEN',
    'get_api_session',
    'get_api_token',
    'set_api_credentials',
    'api_atualizar_tarefa',
    'api_buscar_processo_por_pj',
    'api_buscar_processo_por_ficha',
    'api_atualizar_processo'
]
