from initializr.processos_automacao.classes_processos.ProcessoPan078 import rodar_pan078
from initializr.processos_automacao.classes_processos.ProcessoRodarFlask import Rodar_Flask
from initializr.processos_automacao.classes_processos.ProcessoInsercaoSafra2 import Safra_Insercao_2
from initializr.processos_automacao.classes_processos.ProcessoSafraInsercao import Safra_Insercao
#from initializr.processos_automacao.classes_processos.ProcessoFGTSSafra import Fgts_Safra
#from initializr.processos_automacao.classes_processos.ProcessoDaycovalProposta import Proposta_Daycoval
from initializr.processos_automacao.classes_processos.ProcessoOlePortalOrienta import Ole_Portal_Orienta
#from initializr.processos_automacao.classes_processos.ProcessosDaycovalSimulacao import Daycoval_Simulacao
from initializr.processos_automacao.classes_processos.ProcessoExtrairTagsIccDigital import Extrair_Tags_ICcdigital
from initializr.processos_automacao.classes_processos.ProcessosInsercaoGerarContratoNovaLoja import Ole_Insercao_Gerar_Contrato_Nova_Loja
from initializr.processos_automacao.classes_processos.ProcessosRefinAnexSmsNovaLoja import Ole_Refin_Anex_Sms_Nova_Loja
from initializr.processos_automacao.classes_processos.ProcessoAnexarIccDigital import Itau_Sincronizacao_ICdigital
from initializr.processos_automacao.classes_processos.ProcessosConsultaCpfReceita import Consulta_CPF_Receita
from initializr.processos_automacao.classes_processos.ProcessosConsultaCpfTse import ConsultaCPFJusticaFederal
from initializr.processos_automacao.classes_processos.ProcessosPan import (
    TarefasPan, PanConsultaRefin064, PanConsultaRefin035)
from initializr.processos_automacao.classes_processos.ProcessoConsultaDadosMeuINSS import ConsultaDadosMeuINSS
from initializr.processos_automacao.classes_processos.ProcessosPortalConsignado import PortalConsigSP
from initializr.processos_automacao.classes_processos.ProcessosBMG import BMG
from initializr.processos_automacao.classes_processos.ProcessosItau import (
    ItauInsercaoMca, ItauInsercaoCarolina, ItauInsercao, ItauConsultaRefin,
    ItauConsultaRefinN2, ItauConsultaStatus, Itau_Anexa_Doc_Ajusta_Restricao_Margem, ItauGerarContrato
)
from initializr.processos_automacao.classes_processos.ProcessosBradesco import BradescoSincRefin
from initializr.processos_automacao.classes_processos.ProcessosGoogleAnalytics import GoogleAnalytics
from initializr.processos_automacao.classes_processos.ProcessosMarinha import ConsultaMargemMarinha
from initializr.processos_automacao.classes_processos.ProcessosPromobank import Promobank
from initializr.processos_automacao.classes_processos.ProcessosOle import (
    OleRefinAnexLibSMS, OleSincInsercao, OleConsultaRefin, OleConsigInssCem
)
from initializr.processos_automacao.classes_processos.ProcessoNovoSaque import NovoSaque
from initializr.processos_automacao.classes_processos.ProcessoCora import Cora,CoraLogin